server:
  port: 8081

spring:
  application:
    name: service-provider
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    bus:
      enabled: true
      destination: springCloudBus

eureka:
  instance:
    prefer-ip-address: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh
  endpoint:
    health:
      show-details: always

lab:
  message: "lab5 config message report refresh"
